## Loop Functions
- *lapply*: Loop over a list and evaluate a function on each element
- *sapply*: Same as `lapply` but try to simplify the result
- *apply*: Apply a function over the margins of an array
- *tapply*: Apply a function over subsets of a vector
- *mapply*: Multivariate version of lapply

### lapply

`lapply` **always** retuns a list, regardless of the class of the input

In [7]:
x <- list(a = 1:5, b = rnorm(10))
x

$a
[1] 1 2 3 4 5

$b
 [1]  1.63895583 -1.48353142  0.58095094  0.65163044 -0.01485321  1.40716427
 [7]  0.85488335  0.56365214  0.44843718  1.28682117

In [8]:
lapply(x, mean)

$a
[1] 3

$b
[1] 0.5934111

In [6]:
mean(x$a)

[1] 3

In [9]:
mean(x$b)

[1] 0.5934111

In [10]:
x <- 1:4
lapply(x, runif)

[[1]]
[1] 0.2166978

[[2]]
[1] 0.5115631 0.1552690

[[3]]
[1] 0.07095738 0.35749675 0.62860088

[[4]]
[1] 0.66257896 0.80398814 0.93350765 0.05063952

In [11]:
x <- 1:4
lapply(x, runif, min = 0, max = 10)

[[1]]
[1] 1.743887

[[2]]
[1] 1.155347 7.151485

[[3]]
[1] 2.358458 4.353604 3.130186

[[4]]
[1] 8.402106 7.587849 6.229618 1.593501

In [12]:
x <- list(a = matrix(1:4, 2,2), b = matrix(1:6, 3, 2))
x

$a
     [,1] [,2]
[1,]    1    3
[2,]    2    4

$b
     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

In [13]:
lapply(x, function(elt) elt[,1])

$a
[1] 1 2

$b
[1] 1 2 3

### sapply

`sapply` will try to simplify the result of `lapply` if possible

- If the result is a list where every element is length 1, then a vector is returned
- If the result is a list where every element is a vector of the same length (>1), a matrix is returned
- If it can't figure things out, a list is returned

In [15]:
x <- list(
    a = 1:4,
    b = rnorm(10),
    c = rnorm(20, 1),
    d = rnorm(100, 5)
)
#x

In [16]:
lapply(x, mean)

$a
[1] 2.5

$b
[1] 0.5895294

$c
[1] 1.231044

$d
[1] 5.01808

In [17]:
sapply(x, mean)

a         b         c         d 
2.5000000 0.5895294 1.2310445 5.0180798

In [18]:
mean(x) # returns an error message

Warning message in mean.default(x):
“argument is not numeric or logical: returning NA”


[1] NA

### apply

`apply` is used to evaluate a function (often an anonymous one) over the margins of an array

- It is most often used to apply a function to the rows or columns of a matrix
- It can be used with general arrays, e.g. taking the average of an array of matrices
- It is not really faster than writing a loop, but it works in one line!

For sums and means of matrix dimensions, here are some shortcuts
- `rowSums` = apply(x,1,sum)
- `rowMeans` = apply(x,1,mean)
- `colSums` = apply(x, 2, sum)
- `colMeans` = apply(x,2,mean)

In [19]:
str(apply)

function (X, MARGIN, FUN, ...)  


argument `MARGIN` is an integer vector indicating which margins should be retained

In [21]:
x <- matrix(rnorm(200), 20, 10)
#x

In [26]:
apply(x, 2, mean) # column mean (with argument margin = 2)

[1] -0.42234773 -0.14451480  0.09263102 -0.54826371  0.04103845  0.04946436
 [7] -0.14709157 -0.07860238  0.21287881 -0.09985955

In [24]:
apply(x, 1, sum) # row sum (with argument margin = 1)

[1] -5.1028104  0.2947187  1.0242404 -5.0079050 -2.4975920  1.3476309
 [7]  2.7658228 -6.8045802 -2.5670297  0.8115747 -4.9092968 -6.1676564
[13] -1.5249500  2.9628151 -0.2459875 -1.6468804  1.3032808  0.3757687
[19]  0.4627913  4.2327029

In [28]:
x <- matrix(rnorm(200), 20, 20)
apply(x, 1, quantile, probs = c(0.25, 0.75))

[,1]       [,2]      [,3]       [,4]       [,5]      [,6]       [,7]       
25% -0.3293164 -1.208235 -0.2148967 -0.3936341 -1.076517 -0.1608993 -0.70520445
75%  0.2981084  1.463501  0.5982626  0.6451128  0.188986  0.5748976  0.03444989
    [,8]      [,9]       [,10]      [,11]      [,12]      [,13]     
25% 0.2119727 -0.4498982 -1.4504287 -1.1201617 -0.5653239 -0.5070608
75% 1.2433275  0.8032708  0.1033605 -0.1305911  0.6716183  0.3150976
    [,14]       [,15]     [,16]      [,17]       [,18]     [,19]     
25% -0.59826957 0.2684981 -1.3097704 -0.79940918 0.2076668 -0.7916373
75% -0.09251304 0.4977738  0.3394357  0.06618663 1.1759835  1.1109227
    [,20]      
25% -0.97905520
75%  0.02259531

In [29]:
a <- array(rnorm(2 * 2 * 10), c(2,2,10))
a

, , 1

           [,1]      [,2]
[1,]  1.8588013 1.5937429
[2,] -0.5691397 0.4326189

, , 2

           [,1]      [,2]
[1,] -0.6236025  1.245158
[2,] -0.6632168 -2.186588

, , 3

           [,1]       [,2]
[1,]  0.1083067 -0.6851381
[2,] -0.7864064 -0.2364621

, , 4

           [,1]       [,2]
[1,] -1.7628498  0.5633619
[2,] -0.7651114 -1.2930884

, , 5

         [,1]      [,2]
[1,] 1.635696 -1.220281
[2,] 0.687714  1.416883

, , 6

          [,1]       [,2]
[1,] 0.4121718  0.6062424
[2,] 0.4292163 -1.1286632

, , 7

          [,1]      [,2]
[1,]  1.406707 -1.873955
[2,] -1.128538 -1.004999

, , 8

           [,1]       [,2]
[1,] -0.1800999 -0.8370897
[2,]  0.8518513 -0.6792816

, , 9

          [,1]        [,2]
[1,] -1.597914  0.58114789
[2,] -1.255982 -0.03774694

, , 10

           [,1]       [,2]
[1,] -0.8740989 -1.3409543
[2,]  0.6618332 -0.4759534

In [30]:
apply(a, c(1,2), mean)

[,1]        [,2]      
[1,]  0.03831172 -0.1367765
[2,] -0.25377791 -0.5193281

In [31]:
rowMeans(a, dims = 2)

[,1]        [,2]      
[1,]  0.03831172 -0.1367765
[2,] -0.25377791 -0.5193281

### mapply

`mapply` is a multivariate apply of sorts which applies a function in parallel over a set of arguments

In [32]:
str(mapply)

function (FUN, ..., MoreArgs = NULL, SIMPLIFY = TRUE, USE.NAMES = TRUE)  


Arguments:
- `FUN` is a function to apply
- `...` contains arguments to apply over
- `MoreArgs` is a list of other arguments to `FUN`
- `SIMPLIFY` indicates whether the result should be simplified

In [33]:
list(rep(1,4), rep(2,3), rep(3,2), rep(4,1))

[[1]]
[1] 1 1 1 1

[[2]]
[1] 2 2 2

[[3]]
[1] 3 3

[[4]]
[1] 4

In [34]:
mapply(rep, 1:4, 4:1)

[[1]]
[1] 1 1 1 1

[[2]]
[1] 2 2 2

[[3]]
[1] 3 3

[[4]]
[1] 4

### tapply

 `tapply` is used to apply a function over subsets of a vector. (dont know why it's called `tapply`)

In [35]:
str(tapply)

function (X, INDEX, FUN = NULL, ..., default = NA, simplify = TRUE)  


Arguments
- `X` is a vector
- 'INDEX` is a factor or a list of factors (or else they are coerced to factors)
- `FUN`
- `...`
- `simplify`

In [37]:
x <- c(rnorm(10), runif(10), rnorm(10,1))
f <- gl(3,10)
f

[1] 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3
Levels: 1 2 3

In [39]:
x

[1]  0.08391542  1.10482989 -0.25002942  1.68975046  0.44881648  0.77403422
 [7]  0.24377994  0.93725099 -0.05170638  1.71406207  0.50111123  0.76253946
[13]  0.71263376  0.81557555  0.63048718  0.11502145  0.77790806  0.97269269
[19]  0.50892214  0.10074945 -0.17809673  1.54139769  0.74555708  1.44654864
[25]  1.71266845  0.83956214  3.25161504  1.35170254  0.38821227  0.42758286

In [38]:
tapply(x, f, mean)

1         2         3 
0.6694704 0.5897641 1.1526750

In [40]:
tapply(x, f, mean, simplify = FALSE)

$`1`
[1] 0.6694704

$`2`
[1] 0.5897641

$`3`
[1] 1.152675

### split

`split` takes a vector or other objects and splits it into groups determined by a factor or list of factors

In [42]:
str(split)

function (x, f, drop = FALSE, ...)  


Arguments
- `x` is a vector (or list) or data frame
- `f` is a factor (or coerced to one) or a list of factors
- `drop` indicates whether empty factors levels should be droped

In [43]:
x <- c(rnorm(10), runif(10), rnorm(10, 1))
x

[1]  0.66281217  1.42881575  1.58809650  0.19008302  0.86315241 -1.43398023
 [7]  1.36979070  0.28664205  0.57366649 -0.48231656  0.71816194  0.94824337
[13]  0.64485697  0.25543692  0.38755212  0.30920122  0.58810701  0.04433779
[19]  0.50873729  0.64392660  0.72227712  1.12386474  1.16905731  1.66547934
[25]  2.89656447  2.64449089  0.21911603  2.24069825  2.25912178  0.21574794

In [44]:
f <- gl(3, 10)

In [45]:
split(x, f)

$`1`
 [1]  0.6628122  1.4288158  1.5880965  0.1900830  0.8631524 -1.4339802
 [7]  1.3697907  0.2866420  0.5736665 -0.4823166

$`2`
 [1] 0.71816194 0.94824337 0.64485697 0.25543692 0.38755212 0.30920122
 [7] 0.58810701 0.04433779 0.50873729 0.64392660

$`3`
 [1] 0.7222771 1.1238647 1.1690573 1.6654793 2.8965645 2.6444909 0.2191160
 [8] 2.2406983 2.2591218 0.2157479

In [46]:
lapply(split(x,f), mean)

$`1`
[1] 0.5046762

$`2`
[1] 0.5048561

$`3`
[1] 1.515642

In [51]:
library(datasets)
head(airquality) # data frame

Ozone Solar.R Wind Temp Month Day
1 41    190      7.4 67   5     1  
2 36    118      8.0 72   5     2  
3 12    149     12.6 74   5     3  
4 18    313     11.5 62   5     4  
5 NA     NA     14.3 56   5     5  
6 28     NA     14.9 66   5     6

In [50]:
# split it by month
s <- split(airquality, airquality$Month)
# calculate each column's mean value
lapply (s, function(x) colMeans(x[,c("Ozone", 'Solar.R', 'Wind')]))

$`5`
   Ozone  Solar.R     Wind 
      NA       NA 11.62258 

$`6`
    Ozone   Solar.R      Wind 
       NA 190.16667  10.26667 

$`7`
     Ozone    Solar.R       Wind 
        NA 216.483871   8.941935 

$`8`
   Ozone  Solar.R     Wind 
      NA       NA 8.793548 

$`9`
   Ozone  Solar.R     Wind 
      NA 167.4333  10.1800

In [52]:
sapply(s, function(x) colMeans(x[, c("Ozone", 'Solar.R', 'Wind')]))

5        6         7          8        9       
Ozone         NA        NA         NA       NA       NA
Solar.R       NA 190.16667 216.483871       NA 167.4333
Wind    11.62258  10.26667   8.941935 8.793548  10.1800

In [53]:
sapply(s, function(x) colMeans(x[, c("Ozone", 'Solar.R', 'Wind')],
                              na.rm = T))

5         6         7          8          9        
Ozone    23.61538  29.44444  59.115385  59.961538  31.44828
Solar.R 181.29630 190.16667 216.483871 171.857143 167.43333
Wind     11.62258  10.26667   8.941935   8.793548  10.18000

split on more than 1 level

In [54]:
x <- rnorm(10)
f1 <- gl(2,5)
f2 <- gl(5,2)

In [55]:
f1

[1] 1 1 1 1 1 2 2 2 2 2
Levels: 1 2

In [56]:
f2

[1] 1 1 2 2 3 3 4 4 5 5
Levels: 1 2 3 4 5

In [57]:
interaction(f1,f2)

[1] 1.1 1.1 1.2 1.2 1.3 2.3 2.4 2.4 2.5 2.5
Levels: 1.1 2.1 1.2 2.2 1.3 2.3 1.4 2.4 1.5 2.5

In [58]:
str(split(x, list(f1, f2)))

List of 10
 $ 1.1: num [1:2] -0.985 -1.297
 $ 2.1: num(0) 
 $ 1.2: num [1:2] 0.762 -0.447
 $ 2.2: num(0) 
 $ 1.3: num -0.21
 $ 2.3: num 0.529
 $ 1.4: num(0) 
 $ 2.4: num [1:2] 0.513 2.066
 $ 1.5: num(0) 
 $ 2.5: num [1:2] -0.534 0.229


In [59]:
str(
    split(x, list(f1, f2), drop = T)
)

List of 6
 $ 1.1: num [1:2] -0.985 -1.297
 $ 1.2: num [1:2] 0.762 -0.447
 $ 1.3: num -0.21
 $ 2.3: num 0.529
 $ 2.4: num [1:2] 0.513 2.066
 $ 2.5: num [1:2] -0.534 0.229


## Debugging Tools

In [61]:
log(-1) # warning

Warning message in log(-1):
“NaNs produced”


[1] NaN

### traceback

In [65]:
mean(xx)
traceback()

ERROR: Error in mean(xx): object 'xx' not found


In [66]:
traceback() # seems it only works in terminal mode

No traceback available 


In [68]:
lm(y ~ x) # oh, now traceback is automatically embedded

ERROR: Error in eval(predvars, data, env): object 'y' not found


## Week 3 Quiz

In [70]:
library(datasets)
data(iris)

In [83]:
# ?iris
head(iris)

Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa 
2 4.9          3.0         1.4          0.2         setosa 
3 4.7          3.2         1.3          0.2         setosa 
4 4.6          3.1         1.5          0.2         setosa 
5 5.0          3.6         1.4          0.2         setosa 
6 5.4          3.9         1.7          0.4         setosa

In [75]:
# ?split
str(split)

function (x, f, drop = FALSE, ...)  


In [82]:
#?sapply

In [79]:
apply(split(iris$Sepal.Length, iris$Species), mean)

ERROR: Error in match.fun(FUN): argument "FUN" is missing, with no default


In [90]:
# split iris by Species
s <- split(iris, iris$Species)
irisMeans <- sapply(s, function(x) colMeans(x[, c("Sepal.Length", 'Sepal.Width', 'Petal.Length', 'Petal.Width')]))
#sapply(s, function(x) colMeans(x[, c("Ozone", 'Solar.R', 'Wind')], na.rm = T))
round(irisMeans,1)

setosa versicolor virginica
Sepal.Length 5.0    5.9        6.6      
Sepal.Width  3.4    2.8        3.0      
Petal.Length 1.5    4.3        5.6      
Petal.Width  0.2    1.3        2.0

In [95]:
# colMeans(iris)
# apply(iris[,1:4], 1, mean)
apply(iris[,1:4], 2, mean)
# apply(iris, 2, mean)

Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
    5.843333     3.057333     3.758000     1.199333

In [100]:
library(datasets)
data(mtcars)

In [97]:
?mtcars

mtcars                package:datasets                 R Documentation

_M_o_t_o_r _T_r_e_n_d _C_a_r _R_o_a_d _T_e_s_t_s

_D_e_s_c_r_i_p_t_i_o_n:

     The data was extracted from the 1974 _Motor Trend_ US magazine,
     and comprises fuel consumption and 10 aspects of automobile design
     and performance for 32 automobiles (1973-74 models).

_U_s_a_g_e:

     mtcars
     
_F_o_r_m_a_t:

     A data frame with 32 observations on 11 (numeric) variables.

       [, 1]  mpg   Miles/(US) gallon                        
       [, 2]  cyl   Number of cylinders                      
       [, 3]  disp  Displacement (cu.in.)                    
       [, 4]  hp    Gross horsepower                         
       [, 5]  drat  Rear axle ratio                          
       [, 6]  wt    Weight (1000 lbs)                        
       [, 7]  qsec  1/4 mile time                            
       [, 8]  vs    Engine (0 = V-shaped, 1 = straight)      
       [, 9]  am    Transmission (0 = automatic, 1 = manual) 
       [,10]  gear  Number of forward gears                  
       [,11]  carb  Number of carburetors                    
      
_N_o_t_e:

     Henderson and Velleman (1981) comment in a footnote to Table 1:
     ‘Hocking [original transcriber]'s noncrucial coding of the Mazda's
     rotary engine as a straight six-cylinder engine and the Porsche's
     flat engine as a V engine, as well as the inclusion of the diesel
     Mercedes 240D, have been retained to enable direct comparisons to
     be made with previous analyses.’

_S_o_u_r_c_e:

     Henderson and Velleman (1981), Building multiple regression models
     interactively.  _Biometrics_, *37*, 391-411.

_E_x_a_m_p_l_e_s:

     require(graphics)
     pairs(mtcars, main = "mtcars data", gap = 1/4)
     coplot(mpg ~ disp | as.factor(cyl), data = mtcars,
            panel = panel.smooth, rows = 1)
     ## possibly more meaningful, e.g., for summary() or bivariate plots:
     mtcars2 <- within(mtcars, {
        vs <- factor(vs, labels = c("V", "S"))
        am <- factor(am, labels = c("automatic", "manual"))
        cyl  <- ordered(cyl)
        gear <- ordered(gear)
        carb <- ordered(carb)
     })
     summary(mtcars2)

In [101]:
mtcars

mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4   
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2   
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1   
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4   
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2   
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2   
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4   
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4   
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3   
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3   
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3   
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4   
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4   
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4   
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1   
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2   
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1   
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1   
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2   
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2   
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4   
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2   
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1   
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2   
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2   
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4   
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6   
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8   
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [129]:
# split mtcars by cyl
s <- split(mtcars, mtcars$cyl)
#s
mtcarsMeans <- sapply(s, function(x) colMeans(x[, c("mpg", 'hp')]))
mtcarsMeans
#sapply(s, function(x) colMeans(x[, c("Ozone", 'Solar.R', 'Wind')], na.rm = T))
#round(irisMeans,1)

debugging in: ls(vars, all.names = T)
debug: {
    if (!missing(name)) {
        pos <- tryCatch(name, error = function(e) e)
        if (inherits(pos, "error")) {
            name <- substitute(name)
            if (!is.character(name)) 
                name <- deparse(name)
            warning(gettextf("%s converted to character string", 
                sQuote(name)), domain = NA)
            pos <- name
        }
    }
    all.names <- .Internal(ls(envir, all.names, sorted))
    if (!missing(pattern)) {
        if ((ll <- length(grep("[", pattern, fixed = TRUE))) && 
            ll != length(grep("]", pattern, fixed = TRUE))) {
            if (pattern == "[") {
                pattern <- "\\["
                warning("replaced regular expression pattern '[' by  '\\\\['")
            }
            else if (length(grep("[^\\\\]\\[<-", pattern))) {
                pattern <- sub("\\[<-", "\\\\\\[<-", pattern)
                warning("replaced '[<-' by '\\\\[<-' in regular expression p

4        6         8       
mpg 26.66364  19.74286  15.1000
hp  82.63636 122.28571 209.2143

In [106]:
sapply(
    split(mtcars$mpg, mtcars$cyl), mean
)

4        6        8 
26.66364 19.74286 15.10000

In [107]:
tapply(
    mtcars$mpg, mtcars$cyl, mean
)

4        6        8 
26.66364 19.74286 15.10000

In [108]:
lapply(mtcars, mean)

$mpg
[1] 20.09062

$cyl
[1] 6.1875

$disp
[1] 230.7219

$hp
[1] 146.6875

$drat
[1] 3.596563

$wt
[1] 3.21725

$qsec
[1] 17.84875

$vs
[1] 0.4375

$am
[1] 0.40625

$gear
[1] 3.6875

$carb
[1] 2.8125

In [109]:
split(mtcars, mtcars$cyl)

$`4`
                mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Datsun 710     22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Merc 240D      24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230       22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Fiat 128       32.4   4  78.7  66 4.08 2.200 19.47  1  1    4    1
Honda Civic    30.4   4  75.7  52 4.93 1.615 18.52  1  1    4    2
Toyota Corolla 33.9   4  71.1  65 4.22 1.835 19.90  1  1    4    1
Toyota Corona  21.5   4 120.1  97 3.70 2.465 20.01  1  0    3    1
Fiat X1-9      27.3   4  79.0  66 4.08 1.935 18.90  1  1    4    1
Porsche 914-2  26.0   4 120.3  91 4.43 2.140 16.70  0  1    5    2
Lotus Europa   30.4   4  95.1 113 3.77 1.513 16.90  1  1    5    2
Volvo 142E     21.4   4 121.0 109 4.11 2.780 18.60  1  1    4    2

$`6`
                mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4      21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag  21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Hornet 4 Drive 21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Valiant        18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Merc 280       19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4
Merc 280C      17.8   6 167.6 123 3.92 3.440 18.90  1  0    4    4
Ferrari Dino   19.7   6 145.0 175 3.62 2.770 15.50  0  1    5    6

$`8`
                     mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Hornet Sportabout   18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
Duster 360          14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
Merc 450SE          16.4   8 275.8 180 3.07 4.070 17.40  0  0    3    3
Merc 450SL          17.3   8 275.8 180 3.07 3.730 17.60  0  0    3    3
Merc 450SLC         15.2   8 275.8 180 3.07 3.780 18.00  0  0    3    3
Cadillac Fleetwood  10.4   8 472.0 205 2.93 5.250 17.98  0  0    3    4
Lincoln Continental 10.4   8 460.0 215 3.00 5.424 17.82  0  0    3    4
Chrysler Imperial   14.7   8 440.0 230 3.23 5.345 17.42  0  0    3    4
Dodge Challenger    15.5   8 318.0 150 2.76 3.520 16.87  0  0    3    2
AMC Javelin         15.2   8 304.0 150 3.15 3.435 17.30  0  0    3    2
Camaro Z28          13.3   8 350.0 245 3.73 3.840 15.41  0  0    3    4
Pontiac Firebird    19.2   8 400.0 175 3.08 3.845 17.05  0  0    3    2
Ford Pantera L      15.8   8 351.0 264 4.22 3.170 14.50  0  1    5    4
Maserati Bora       15.0   8 301.0 335 3.54 3.570 14.60  0  1    5    8

In [110]:
apply(mtcars, 2, mean)

mpg        cyl       disp         hp       drat         wt       qsec 
 20.090625   6.187500 230.721875 146.687500   3.596563   3.217250  17.848750 
        vs         am       gear       carb 
  0.437500   0.406250   3.687500   2.812500

In [111]:
sapply(mtcars, cyl, mean)

ERROR: Error in match.fun(FUN): object 'cyl' not found


In [112]:
mean(mtcars$mpg, mtcars$cyl)

ERROR: Error in mean.default(mtcars$mpg, mtcars$cyl): 'trim' must be numeric of length one


In [113]:
tapply(mtcars$cyl, mtcars$mpg, mean)

10.4 13.3 14.3 14.7   15 15.2 15.5 15.8 16.4 17.3 17.8 18.1 18.7 19.2 19.7   21 
   8    8    8    8    8    8    8    8    8    8    6    6    8    7    6    6 
21.4 21.5 22.8 24.4   26 27.3 30.4 32.4 33.9 
   5    4    4    4    4    4    4    4    4

In [114]:
with(mtcars, tapply(mpg, cyl, mean))

4        6        8 
26.66364 19.74286 15.10000

In [115]:
# split mtcars by cyl
s <- split(mtcars, mtcars$cyl)
#s
mtcarsMeans_hp <- sapply(s, function(x) colMeans(x[, c("mpg", 'hp')]))
mtcarsMeans_hp
#sapply(s, function(x) colMeans(x[, c("Ozone", 'Solar.R', 'Wind')], na.rm = T))
#round(irisMeans,1)

4        6         8       
mpg 26.66364  19.74286  15.1000
hp  82.63636 122.28571 209.2143

In [119]:
mtcarsMeans_hp[2,]

4         6         8 
 82.63636 122.28571 209.21429

In [123]:
round(abs(mtcarsMeans_hp[2,1] - mtcarsMeans_hp[2,3]),1)

[1] 126.6

In [126]:
debug(ls)
ls

function (name, pos = -1L, envir = as.environment(pos), all.names = FALSE, 
    pattern, sorted = TRUE) 
{
    if (!missing(name)) {
        pos <- tryCatch(name, error = function(e) e)
        if (inherits(pos, "error")) {
            name <- substitute(name)
            if (!is.character(name)) 
                name <- deparse(name)
            warning(gettextf("%s converted to character string", 
                sQuote(name)), domain = NA)
            pos <- name
        }
    }
    all.names <- .Internal(ls(envir, all.names, sorted))
    if (!missing(pattern)) {
        if ((ll <- length(grep("[", pattern, fixed = TRUE))) && 
            ll != length(grep("]", pattern, fixed = TRUE))) {
            if (pattern == "[") {
                pattern <- "\\["
                warning("replaced regular expression pattern '[' by  '\\\\['")
            }
            else if (length(grep("[^\\\\]\\[<-", pattern))) {
                pattern <- sub("\\[<-", "\\\\\\[<-", pattern)
                warning("replaced '[<-' by '\\\\[<-' in regular expression pattern")
            }
        }
        grep(pattern, all.names, value = TRUE)
    }
    else all.names
}
<bytecode: 0x1f1ddb8>
<environment: namespace:base>

## Week 3 Quiz

In [134]:
# makeVector.R
makeVector <- function(x = numeric()){
    m <- NULL
    set <- function(y) {
        x <<- y
        m <<- NULL
    }
    get <- function() x
    setmean <- function(mean) m <<- mean
    getmean <- function() m
    list(set = set, get = get, 
        setmean = setmean,
        getmean = getmean)
}

In [135]:
# cachemean.R
cachemean <- function(x, ...){
    m <- x$getmean()
    if(!is.null(m)){
        message('getting cached data')
        return(m)
    }
    data <- x$get()
    m <- mean(data, ...)
    x$setmean(m)
}

In [137]:
# cacheMatrix.R
## Put comments here that give an overall description of what your
## functions do

## Write a short comment describing this function

makeCacheMatrix <- function(x = matrix()) {
    # Initialize the inverse property
    i <- NULL
    
    # Method to set the matrix
    set <- function(matrix) {
        m <<- matrix
        i <<- NULL
    }
    
    # Method to get the matrix
    get <- function() {
        ## return the matrix
        m
    }
    
    # Method to set the inverse of the matrix
    setInverse <- function(inverse) {
        i <<- inverse
    }
    
    ## Method to get the inverse of the matrix
    getInverse <- function() {
        ## Return the inverse property
        i
    }

    # Return a list of the methods
    list(set = set, get = get, setInverse = setInverse, getInverse = getInverse)
}

In [138]:
# cacheSolve.R
# Compute the inverse of the special matrix returned by "makeCacheMatrix"
# above. If the inverse has already been calculated (and the matrix has not
# changed), then the "cachesolve" should retrieve the inverse from the cache

cacheSolve <- function(x, ...) {
    ## Return a matrix that is the inverse of 'x'
    m <- x$getInverse()
    
    ## Just return the inverse if it already exists
    if(!is.null(m)){
        message("getting cached data")
        return(m)
    }
    
    ## Get the matrix from our object
    data <- x$get()
    
    ## Calculate the inverse using matrix multiplication
    m <- solve(data) %*% data
    
    ## Set the inverse to the object
    x$setInverse(m)
    
    ## Return the matrix
    m
}